# -*- coding: utf-8 -*-
"""dropna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqYsId0bAXRMKmVHSYzkUb4bU0YxqTTc
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.head()

df.tail()

df.isnull().sum()

df.dropna(subset=['self_employed'], inplace=True)

df.isnull().sum()