# -*- coding: utf-8 -*-
"""fillna 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14p9N6ilXip5MGsEW-GA2y71a5LYPGOK7
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.head()

df.tail()

df.isnull().sum()

mode_value = df['self_employed'].mode()[0]
df['self_employed'].fillna(mode_value, inplace=True)

df.isnull().sum()