# -*- coding: utf-8 -*-
"""fillna

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9sEgsobGEuf5esWXYYB12JTmanqATT0
"""

import pandas as pd

df=pd.read_csv("/content/Mental Health Dataset.csv")
df.head()

df.head()

df.tail()

df.isnull().sum()

df['self_employed'].fillna('unknown',inplace=True)

df.isnull().sum()